name = "fast-agent"
kind = "acp"
description = "Code and build agents with comprehensive multi-provider support"
homepage = "https://fast-agent.ai"
aliases = ["fast-agent", "https://github.com/evalstate/fast-agent"]
categories = ["agent-client-protocol", "assistant"]

[version]
tag-source = "static:0.9.2"

[[artifact]]
os = "windows"
arch = "x86_64"
source = { uvx = "fast-agent-acp==0.9.2" }
bin = "fast-agent"
args = ["-x"]

[[artifact]]
os = "windows"
arch = "aarch64"
source = { uvx = "fast-agent-acp==0.9.2" }
bin = "fast-agent"
args = ["-x"]

[[artifact]]
os = "linux"
arch = "x86_64"
source = { uvx = "fast-agent-acp==0.9.2" }
bin = "fast-agent"
args = ["-x"]

[[artifact]]
os = "linux"
arch = "aarch64"
source = { uvx = "fast-agent-acp==0.9.2" }
bin = "fast-agent"
args = ["-x"]

[[artifact]]
os = "macos"
arch = "aarch64"
source = { uvx = "fast-agent-acp==0.9.2" }
bin = "fast-agent"
args = ["-x"]

[[artifact]]
os = "macos"
arch = "x86_64"
source = { uvx = "fast-agent-acp==0.9.2" }
bin = "fast-agent"
args = ["-x"]
