name = "junie"
kind = "acp"
description = "AI Coding Agent by JetBrains"
homepage = "https://junie.jetbrains.com"
aliases = ["Junie", "https://github.com/JetBrains/junie"]
categories = ["agent-client-protocol", "assistant"]

[version]
tag-source = "static:2144.7.0"

[[artifact]]
os = "macos"
arch = "aarch64"
source = { archive = "https://github.com/JetBrains/junie/releases/download/2144.7/junie-release-2144.7-macos-aarch64.zip" }
bin = "Applications/junie.app/Contents/MacOS/junie"
args = ["--acp=true"]

[[artifact]]
os = "macos"
arch = "x86_64"
source = { archive = "https://github.com/JetBrains/junie/releases/download/2144.7/junie-release-2144.7-macos-amd64.zip" }
bin = "Applications/junie.app/Contents/MacOS/junie"
args = ["--acp=true"]

[[artifact]]
os = "linux"
arch = "aarch64"
source = { archive = "https://github.com/JetBrains/junie/releases/download/2144.7/junie-release-2144.7-linux-aarch64.zip" }
bin = "junie-app/bin/junie"
args = ["--acp=true"]

[[artifact]]
os = "linux"
arch = "x86_64"
source = { archive = "https://github.com/JetBrains/junie/releases/download/2144.7/junie-release-2144.7-linux-amd64.zip" }
bin = "junie-app/bin/junie"
args = ["--acp=true"]

[[artifact]]
os = "windows"
arch = "x86_64"
source = { archive = "https://github.com/JetBrains/junie/releases/download/2144.7/junie-release-2144.7-windows-amd64.zip" }
bin = "junie/junie.exe"
args = ["--acp=true"]
