//! Shared UI model for frontend-agnostic rendering.
//!
//! Commands mutate `Model` directly. Frontends read it and render.
//! No action enum indirection — the model is the single source of truth.
//!
//! All content uses trait objects (`Box<dyn ContentModel>`) instead of
//! enums, so new model types can be added without modifying this module.
//! Downcasting to concrete types uses Rust's trait upcasting — no manual
//! `as_any()` boilerplate is needed.

mod models;

pub use models::{
    AssistantBubbleDisplay, AssistantBubbleMeta, AssistantBubbleSide, AssistantContextItem,
    AssistantEntry, AssistantEntryDetailLine, AssistantEntryDetails, AssistantEntryDisplay,
    AssistantEntryKind, AssistantEntryRole, AssistantEntryRow, AssistantEntryTone, AssistantFollow,
    AssistantHeaderItem, AssistantHeaderModel, AssistantHeaderTone, AssistantHistoryEntry,
    AssistantModel, AssistantPlanItem, AssistantPlanRow, AssistantPlanSection, AssistantPlanStatus,
    AssistantPlanTone, AssistantStatusItem, AssistantStatusItemKind, AssistantTab,
    AssistantTerminal, AssistantTextFormat, CompletionItem, CompletionModel, PickerCell,
    PickerColumnHeader, PickerItemData, PickerModel, PickerPreview, PickerRow, PromptModel,
};
// Re-export PluginPanelModel (defined here, not in `models` submodule)

use std::any::Any;
use std::fmt::Debug;
use std::path::PathBuf;

use helix_core::Position;
use slotmap::SlotMap;

slotmap::new_key_type! {
    pub struct PanelId;
}

slotmap::new_key_type! {
    pub struct FloatId;
}

/// Marker type for layer IDs.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum LayerKind {}

/// Stable ID for a layer. Generated by `Model::next_layer_id()`.
pub type LayerId = crate::id::Id<LayerKind>;

// ─── Content model trait ───────────────────────────────────────────────

/// Unified trait for all UI content models (layers, panels, floats).
///
/// Any type stored as content in a `LayerEntry`, `PanelEntry`, or
/// `FloatEntry` implements this trait. The `tag()` method provides a
/// stable string identifier for the model type (e.g. "picker", "assistant-panel",
/// "text").
///
/// Downcasting to concrete types uses Rust's trait upcasting (stable since
/// 1.76): `dyn ContentModel` can be coerced to `&dyn Any`, so no manual
/// `as_any()` boilerplate is needed. Convenience methods `downcast_ref`,
/// `downcast_mut`, and `is` are provided as inherent methods on
/// `dyn ContentModel`.
pub trait ContentModel: Debug + Send + Sync + Any {
    /// Stable identifier for this model type. Used for matching in
    /// event routing and debugging (e.g. "picker", "assistant-panel", "text").
    fn tag(&self) -> &str;
}

/// Inherent methods on `dyn ContentModel` for type-safe downcasting.
///
/// These leverage trait upcasting (`dyn ContentModel` → `dyn Any`) so
/// implementations don't need manual `as_any()` methods.
impl dyn ContentModel {
    /// Downcast to a concrete model type by reference.
    pub fn downcast_ref<T: 'static>(&self) -> Option<&T> {
        (self as &dyn Any).downcast_ref()
    }

    /// Downcast to a concrete model type by mutable reference.
    pub fn downcast_mut<T: 'static>(&mut self) -> Option<&mut T> {
        (self as &mut dyn Any).downcast_mut()
    }

    /// Check whether this model is a specific concrete type.
    pub fn is<T: 'static>(&self) -> bool {
        (self as &dyn Any).is::<T>()
    }
}

/// Implement `ContentModel` for a concrete type with a static tag.
///
/// ```ignore
/// crate::impl_content_model!(PickerModel, "picker");
/// ```
#[macro_export]
macro_rules! impl_content_model {
    ($ty:ty, $tag:expr) => {
        impl $crate::model::ContentModel for $ty {
            fn tag(&self) -> &str {
                $tag
            }
        }
    };
}

// ─── Built-in ContentModel impls ──────────────────────────────────────

// Layers
crate::impl_content_model!(PickerModel, "picker");
crate::impl_content_model!(PromptModel, "prompt");
crate::impl_content_model!(CompletionModel, "completion");
crate::impl_content_model!(PluginLayerModel, "plugin");

// Panels
crate::impl_content_model!(AssistantModel, "assistant-panel");
crate::impl_content_model!(ListPanelModel, "list");
crate::impl_content_model!(TreePanelModel, "tree");
crate::impl_content_model!(BlocksPanelModel, "blocks");
crate::impl_content_model!(PluginPanelModel, "plugin_panel");

// Floats
crate::impl_content_model!(TextFloatModel, "text");
crate::impl_content_model!(DocumentFloatModel, "document");
crate::impl_content_model!(PluginFloatModel, "plugin_render");

// ─── Model ────────────────────────────────────────────────────────────

/// Root UI state. Commands mutate this; frontends render it.
#[derive(Debug)]
pub struct Model {
    /// Ordered layer stack (bottom to top), rendered in order.
    pub layers: Vec<LayerEntry>,

    /// Persistent side panels (assistant, file tree, diagnostics, etc.).
    /// SlotMap for stable IDs — panels can be added/removed without index shifts.
    pub panels: SlotMap<PanelId, PanelEntry>,

    /// Persistent floating windows. Rendered above panels, below modal layers.
    pub floats: SlotMap<FloatId, FloatEntry>,

    /// Status line / transient notifications.
    pub status: Option<StatusMessage>,

    /// What currently has input focus.
    pub focus: FocusTarget,

    /// Focus history stack for returning after dismissals. Bounded to 16 entries.
    focus_history: Vec<FocusTarget>,

    /// Counter for allocating unique layer IDs.
    next_layer_id: usize,
}

impl Default for Model {
    fn default() -> Self {
        Self {
            layers: Vec::new(),
            panels: SlotMap::default(),
            floats: SlotMap::default(),
            status: None,
            focus: FocusTarget::Editor,
            focus_history: Vec::new(),
            next_layer_id: 0,
        }
    }
}

impl Model {
    /// Allocate a new layer ID. Call when pushing a layer.
    pub fn next_layer_id(&mut self) -> LayerId {
        let id = LayerId::new(self.next_layer_id);
        self.next_layer_id = self.next_layer_id.saturating_add(1);
        id
    }

    /// Push a new layer onto the stack and focus it. Returns its `LayerId`.
    pub fn push_layer(&mut self, content: Box<dyn ContentModel>, placement: Placement) -> LayerId {
        let id = self.next_layer_id();
        self.layers.push(LayerEntry {
            id,
            content,
            placement,
        });
        self.focus = FocusTarget::Layer(id);
        id
    }

    /// Remove a layer by ID. Returns `true` if found. Resets focus to editor
    /// if the removed layer was focused.
    pub fn remove_layer(&mut self, id: LayerId) -> bool {
        let was_focused = self.focus == FocusTarget::Layer(id);
        let idx = self.layers.iter().position(|l| l.id == id);
        if let Some(idx) = idx {
            self.layers.remove(idx);
            if was_focused {
                self.focus = self
                    .layers
                    .last()
                    .map(|l| FocusTarget::Layer(l.id))
                    .unwrap_or(FocusTarget::Editor);
            }
            true
        } else {
            false
        }
    }

    /// Pop the topmost layer. Returns its entry if the stack was non-empty.
    pub fn pop_layer(&mut self) -> Option<LayerEntry> {
        let entry = self.layers.pop();
        if let Some(ref e) = entry {
            if self.focus == FocusTarget::Layer(e.id) {
                self.focus = self
                    .layers
                    .last()
                    .map(|l| FocusTarget::Layer(l.id))
                    .unwrap_or(FocusTarget::Editor);
            }
        }
        entry
    }

    /// Get a reference to the topmost layer, if any.
    pub fn top_layer(&self) -> Option<&LayerEntry> {
        self.layers.last()
    }

    /// Get a mutable reference to a layer by ID.
    pub fn layer_mut(&mut self, id: LayerId) -> Option<&mut LayerEntry> {
        self.layers.iter_mut().find(|l| l.id == id)
    }

    /// Downcast a layer's content to a concrete model type.
    pub fn layer_model_mut<M: 'static>(&mut self, id: LayerId) -> Option<&mut M> {
        self.layer_mut(id)
            .and_then(|l| l.content.downcast_mut::<M>())
    }

    /// Check if any layer contains a model of type `M`.
    pub fn has_layer<M: 'static>(&self) -> bool {
        self.layers.iter().any(|l| l.content.is::<M>())
    }

    /// Insert a panel. Returns its `PanelId`.
    pub fn insert_panel(
        &mut self,
        title: impl Into<String>,
        content: Box<dyn ContentModel>,
        side: PanelSide,
        size: PanelSize,
    ) -> PanelId {
        let title = title.into();
        self.panels.insert_with_key(|id| PanelEntry {
            id,
            title,
            content,
            side,
            size,
            visible: true,
        })
    }

    /// Downcast a panel's content to a concrete model type.
    pub fn panel_model_mut<M: 'static>(&mut self, id: PanelId) -> Option<&mut M> {
        self.panels
            .get_mut(id)
            .and_then(|p| p.content.downcast_mut::<M>())
    }

    /// Remove a panel by ID. Returns `true` if found.
    pub fn remove_panel(&mut self, id: PanelId) -> bool {
        if self.focus == FocusTarget::Panel(id) {
            self.pop_focus();
        }
        self.panels.remove(id).is_some()
    }

    /// Toggle a panel's visibility. Returns the new visibility state.
    pub fn toggle_panel(&mut self, id: PanelId) -> Option<bool> {
        let panel = self.panels.get_mut(id)?;
        panel.visible = !panel.visible;
        let visible = panel.visible;
        // If hiding and it was focused, return focus
        if !visible && self.focus == FocusTarget::Panel(id) {
            self.pop_focus();
        }
        Some(visible)
    }

    /// Focus a panel. Pushes the current focus onto the history stack.
    pub fn focus_panel(&mut self, id: PanelId) {
        if let Some(panel) = self.panels.get(id) {
            if panel.visible {
                self.push_focus(FocusTarget::Panel(id));
            }
        }
    }

    // ─── Float management ──────────────────────────────────────────────

    /// Create a floating window. Returns its `FloatId`.
    pub fn create_float(
        &mut self,
        content: Box<dyn ContentModel>,
        placement: Placement,
        title: Option<String>,
        dismissible: bool,
        focus: bool,
    ) -> FloatId {
        let id = self.floats.insert_with_key(|id| FloatEntry {
            id,
            title,
            content,
            placement,
            dismissible,
            owner: None,
        });
        if focus {
            self.push_focus(FocusTarget::Float(id));
        }
        id
    }

    /// Get a reference to a float by ID.
    pub fn float(&self, id: FloatId) -> Option<&FloatEntry> {
        self.floats.get(id)
    }

    /// Get a mutable reference to a float by ID.
    pub fn float_mut(&mut self, id: FloatId) -> Option<&mut FloatEntry> {
        self.floats.get_mut(id)
    }

    /// Downcast a float's content to a concrete model type.
    pub fn float_model_mut<M: 'static>(&mut self, id: FloatId) -> Option<&mut M> {
        self.floats
            .get_mut(id)
            .and_then(|f| f.content.downcast_mut::<M>())
    }

    /// Close a float by ID. Returns `true` if found.
    pub fn close_float(&mut self, id: FloatId) -> bool {
        if self.focus == FocusTarget::Float(id) {
            self.pop_focus();
        }
        self.floats.remove(id).is_some()
    }

    /// Remove all floats owned by a specific plugin.
    pub fn remove_floats_by_owner(&mut self, owner: &str) {
        let ids: Vec<FloatId> = self
            .floats
            .iter()
            .filter(|(_, f)| f.owner.as_deref() == Some(owner))
            .map(|(id, _)| id)
            .collect();
        for id in ids {
            self.close_float(id);
        }
    }

    // ─── Focus management ──────────────────────────────────────────────

    /// Push the current focus onto the history stack and set a new focus target.
    pub fn push_focus(&mut self, target: FocusTarget) {
        if self.focus != target {
            self.focus_history.push(self.focus);
            // Bound the history stack
            if self.focus_history.len() > 16 {
                self.focus_history.remove(0);
            }
            self.focus = target;
        }
    }

    /// Pop the focus history, restoring the previous focus target.
    pub fn pop_focus(&mut self) {
        self.focus = self.focus_history.pop().unwrap_or(FocusTarget::Editor);
    }

    // ─── Status & queries ──────────────────────────────────────────────

    /// Set the status message. Pass `None` to clear.
    pub fn set_status(&mut self, msg: Option<StatusMessage>) {
        self.status = msg;
    }

    /// Find the first layer matching a predicate.
    pub fn find_layer(&self, predicate: impl Fn(&LayerEntry) -> bool) -> Option<&LayerEntry> {
        self.layers.iter().find(|l| predicate(l))
    }
}

// ─── Layer / Panel entries ──────────────────────────────────────────────

/// A single layer in the compositor stack.
pub struct LayerEntry {
    pub id: LayerId,
    /// Typed content model for rendering. Downcast to concrete type via
    /// `content.downcast_ref::<T>()`.
    pub content: Box<dyn ContentModel>,
    pub placement: Placement,
}

// Manual Debug for cleaner output — shows tag instead of full content.
impl Debug for LayerEntry {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("LayerEntry")
            .field("id", &self.id)
            .field("tag", &self.content.tag())
            .field("placement", &self.placement)
            .finish()
    }
}

/// How a layer or float is positioned.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Placement {
    Fullscreen,
    Centered {
        width: u16,
        height: u16,
    },
    Float {
        x: u16,
        y: u16,
        width: u16,
        height: u16,
    },
    Anchored {
        view: crate::ViewId,
        anchor: Position,
        width: u16,
        height: u16,
        bias: crate::layout::AnchorBias,
    },
}

/// Plugin layer model — structured data for frontend rendering.
#[derive(Debug, Clone)]
pub struct PluginLayerModel {
    pub plugin_id: String,
    pub title: String,
    pub content: Vec<RenderBlock>,
}

/// Styled text block or interactive region for plugin rendering.
#[derive(Debug, Clone)]
pub struct RenderBlock {
    pub text: String,
    pub style: Option<crate::graphics::Style>,
}

/// A persistent docked panel — generic container for side content.
///
/// The content's `tag()` identifies the model type. The `title` field
/// is for display. Event routing uses the panel's `PanelId` and the
/// model's `tag()`.
pub struct PanelEntry {
    pub id: PanelId,
    /// Display title shown in the panel header (e.g. "Agent", "Files").
    pub title: String,
    /// Typed content model for rendering. Downcast to concrete type via
    /// `content.downcast_ref::<T>()`.
    pub content: Box<dyn ContentModel>,
    /// Which edge the panel is docked to.
    pub side: PanelSide,
    /// How much space the panel takes.
    pub size: PanelSize,
    /// Whether the panel is currently visible.
    pub visible: bool,
}

impl PanelEntry {
    /// The content model's tag (e.g. "chat", "list", "tree").
    pub fn tag(&self) -> &str {
        self.content.tag()
    }
}

impl Debug for PanelEntry {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("PanelEntry")
            .field("id", &self.id)
            .field("title", &self.title)
            .field("tag", &self.content.tag())
            .field("side", &self.side)
            .field("size", &self.size)
            .finish()
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PanelSide {
    Left,
    Right,
    Bottom,
}

/// Panel sizing — alias for the shared `Size` enum from layout.
pub type PanelSize = crate::layout::Size;

/// Freeform styled blocks panel model. For custom plugin UIs that don't
/// fit the chat/list/tree patterns.
#[derive(Debug, Clone, Default)]
pub struct BlocksPanelModel {
    pub blocks: Vec<RenderBlock>,
}

/// List panel model — flat item list with selection.
#[derive(Debug, Clone, Default)]
pub struct ListPanelModel {
    pub items: Vec<ListPanelItem>,
    pub selection: Option<usize>,
}

/// An item in a list panel.
#[derive(Debug, Clone)]
pub struct ListPanelItem {
    pub text: String,
    pub detail: Option<String>,
    pub severity: Option<String>,
    pub path: Option<PathBuf>,
    pub line: Option<usize>,
}

/// Tree panel model — hierarchical expandable nodes.
#[derive(Debug, Clone, Default)]
pub struct TreePanelModel {
    pub root: PathBuf,
    pub items: Vec<TreePanelNode>,
    pub selection: Option<usize>,
}

/// A node in a tree panel.
#[derive(Debug, Clone)]
pub struct TreePanelNode {
    pub label: String,
    pub path: Option<PathBuf>,
    pub is_dir: bool,
    pub depth: usize,
    pub expanded: bool,
}

/// Plugin panel model marker.
///
/// Callback routing is keyed by the typed `PanelHandle` returned at
/// registration time, so the model entry only needs to identify the panel
/// content kind for layout/snapshot purposes.
#[derive(Debug, Clone, Copy, Default)]
pub struct PluginPanelModel;

// ─── Float entries ─────────────────────────────────────────────────────

/// A persistent floating window overlay.
pub struct FloatEntry {
    pub id: FloatId,
    pub title: Option<String>,
    /// Typed content model for rendering. Downcast to concrete type via
    /// `content.downcast_ref::<T>()`.
    pub content: Box<dyn ContentModel>,
    pub placement: Placement,
    /// If true, clicking outside or pressing Escape closes the float.
    pub dismissible: bool,
    /// Which plugin owns this float (for cleanup on plugin unload).
    pub owner: Option<String>,
}

impl Debug for FloatEntry {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("FloatEntry")
            .field("id", &self.id)
            .field("title", &self.title)
            .field("tag", &self.content.tag())
            .field("placement", &self.placement)
            .field("dismissible", &self.dismissible)
            .finish()
    }
}

/// Float model for styled text blocks.
#[derive(Debug, Clone, Default)]
pub struct TextFloatModel {
    pub blocks: Vec<RenderBlock>,
}

/// Float model for rendering a live document snapshot in an overlay.
#[derive(Debug, Clone, Copy)]
pub struct DocumentFloatModel {
    pub document: crate::DocumentId,
}

/// Float model for plugin-rendered content.
#[derive(Debug, Clone)]
pub struct PluginFloatModel {
    pub plugin_name: String,
    pub render_callback_id: u64,
}

// ─── Status ────────────────────────────────────────────────────────────

#[derive(Debug, Clone)]
pub struct StatusMessage {
    pub text: String,
    pub timeout_ms: Option<u64>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum FocusTarget {
    /// The main editor split tree (delegates to `tree.focus`).
    Editor,
    /// A modal layer (prompt, picker, completion).
    Layer(LayerId),
    /// A docked panel.
    Panel(PanelId),
    /// A floating window.
    Float(FloatId),
}

// Re-export the old type alias for transition period.
pub type ChatPanelModel = AssistantModel;

#[cfg(test)]
mod tests {
    use super::*;

    // ─── Layer lifecycle ────────────────────────────────────────────

    #[test]
    fn push_layer_assigns_unique_ids() {
        let mut ui = Model::default();
        let id1 = ui.push_layer(Box::new(PickerModel::default()), Placement::Fullscreen);
        let id2 = ui.push_layer(Box::new(PromptModel::default()), Placement::Fullscreen);
        assert_ne!(id1, id2);
        assert_eq!(ui.layers.len(), 2);
    }

    #[test]
    fn push_layer_focuses_new_layer() {
        let mut ui = Model::default();
        assert_eq!(ui.focus, FocusTarget::Editor);
        let id = ui.push_layer(Box::new(PickerModel::default()), Placement::Fullscreen);
        assert_eq!(ui.focus, FocusTarget::Layer(id));
    }

    #[test]
    fn pop_layer_restores_focus() {
        let mut ui = Model::default();
        let id1 = ui.push_layer(Box::new(PickerModel::default()), Placement::Fullscreen);
        let _id2 = ui.push_layer(Box::new(PromptModel::default()), Placement::Fullscreen);
        ui.pop_layer();
        assert_eq!(ui.focus, FocusTarget::Layer(id1));
        ui.pop_layer();
        assert_eq!(ui.focus, FocusTarget::Editor);
    }

    #[test]
    fn pop_empty_returns_none() {
        let mut ui = Model::default();
        assert!(ui.pop_layer().is_none());
    }

    #[test]
    fn remove_layer_by_id() {
        let mut ui = Model::default();
        let id1 = ui.push_layer(Box::new(PickerModel::default()), Placement::Fullscreen);
        let id2 = ui.push_layer(Box::new(PromptModel::default()), Placement::Fullscreen);
        assert!(ui.remove_layer(id1));
        assert_eq!(ui.layers.len(), 1);
        assert_eq!(ui.layers[0].id, id2);
    }

    #[test]
    fn remove_focused_layer_refocuses() {
        let mut ui = Model::default();
        let id1 = ui.push_layer(Box::new(PickerModel::default()), Placement::Fullscreen);
        let id2 = ui.push_layer(Box::new(PromptModel::default()), Placement::Fullscreen);
        assert_eq!(ui.focus, FocusTarget::Layer(id2));
        ui.remove_layer(id2);
        assert_eq!(ui.focus, FocusTarget::Layer(id1));
    }

    #[test]
    fn remove_nonexistent_layer_returns_false() {
        let mut ui = Model::default();
        assert!(!ui.remove_layer(LayerId::new(999)));
    }

    // ─── Layer model access (generic) ───────────────────────────────

    #[test]
    fn layer_model_mut_downcasts_correctly() {
        let mut ui = Model::default();
        let id = ui.push_layer(Box::new(PickerModel::default()), Placement::Fullscreen);
        let model = ui.layer_model_mut::<PickerModel>(id).unwrap();
        model.query = "test".into();
        assert_eq!(ui.layer_model_mut::<PickerModel>(id).unwrap().query, "test");
    }

    #[test]
    fn layer_model_mut_returns_none_for_wrong_type() {
        let mut ui = Model::default();
        let id = ui.push_layer(Box::new(PickerModel::default()), Placement::Fullscreen);
        assert!(ui.layer_model_mut::<PromptModel>(id).is_none());
    }

    #[test]
    fn has_layer_reflects_state() {
        let mut ui = Model::default();
        assert!(!ui.has_layer::<PickerModel>());
        let id = ui.push_layer(Box::new(PickerModel::default()), Placement::Fullscreen);
        assert!(ui.has_layer::<PickerModel>());
        ui.remove_layer(id);
        assert!(!ui.has_layer::<PickerModel>());
    }

    // ─── Panel lifecycle ────────────────────────────────────────────

    #[test]
    fn insert_and_remove_panel() {
        let mut ui = Model::default();
        let id = ui.insert_panel(
            "Test Panel",
            Box::new(BlocksPanelModel::default()),
            PanelSide::Right,
            PanelSize::Percent(30),
        );
        assert_eq!(ui.panels.len(), 1);
        assert_eq!(ui.panels[id].tag(), "blocks");
        assert_eq!(ui.panels[id].title, "Test Panel");
        assert!(ui.remove_panel(id));
        assert_eq!(ui.panels.len(), 0);
    }

    #[test]
    fn remove_focused_panel_resets_focus() {
        let mut ui = Model::default();
        let id = ui.insert_panel(
            "Agent",
            Box::new(AssistantModel::default()),
            PanelSide::Right,
            PanelSize::Percent(35),
        );
        ui.focus = FocusTarget::Panel(id);
        ui.remove_panel(id);
        assert_eq!(ui.focus, FocusTarget::Editor);
    }

    #[test]
    fn panel_model_mut_downcasts_correctly() {
        let mut ui = Model::default();
        let id = ui.insert_panel(
            "Agent",
            Box::new(AssistantModel::default()),
            PanelSide::Right,
            PanelSize::Percent(35),
        );
        let model = ui.panel_model_mut::<AssistantModel>(id).unwrap();
        model.agent_name = "Claude Code".into();
        assert_eq!(
            ui.panel_model_mut::<AssistantModel>(id).unwrap().agent_name,
            "Claude Code"
        );
    }

    // ─── Status ─────────────────────────────────────────────────────

    #[test]
    fn set_and_clear_status() {
        let mut ui = Model::default();
        assert!(ui.status.is_none());
        ui.set_status(Some(StatusMessage {
            text: "hello".into(),
            timeout_ms: Some(3000),
        }));
        assert_eq!(ui.status.as_ref().unwrap().text, "hello");
        ui.set_status(None);
        assert!(ui.status.is_none());
    }

    // ─── Multiple layers + panels coexist ───────────────────────────

    #[test]
    fn layers_and_panels_independent() {
        let mut ui = Model::default();
        let layer_id = ui.push_layer(Box::new(PickerModel::default()), Placement::Fullscreen);
        let panel_id = ui.insert_panel(
            "Files",
            Box::new(TreePanelModel::default()),
            PanelSide::Left,
            PanelSize::fixed(30),
        );
        assert_eq!(ui.layers.len(), 1);
        assert_eq!(ui.panels.len(), 1);

        ui.remove_layer(layer_id);
        assert_eq!(ui.layers.len(), 0);
        assert_eq!(ui.panels.len(), 1);

        ui.push_layer(Box::new(PromptModel::default()), Placement::Fullscreen);
        ui.remove_panel(panel_id);
        assert_eq!(ui.layers.len(), 1);
        assert_eq!(ui.panels.len(), 0);
    }

    // ─── Float lifecycle ────────────────────────────────────────────

    #[test]
    fn create_and_close_float() {
        let mut ui = Model::default();
        let id = ui.create_float(
            Box::new(TextFloatModel::default()),
            Placement::Centered {
                width: 60,
                height: 20,
            },
            Some("Preview".into()),
            false,
            false,
        );
        assert_eq!(ui.floats.len(), 1);
        assert_eq!(ui.floats[id].title.as_deref(), Some("Preview"));
        assert_eq!(ui.focus, FocusTarget::Editor); // didn't focus
        assert!(ui.close_float(id));
        assert_eq!(ui.floats.len(), 0);
    }

    #[test]
    fn create_float_with_focus() {
        let mut ui = Model::default();
        let id = ui.create_float(
            Box::new(TextFloatModel::default()),
            Placement::Centered {
                width: 40,
                height: 10,
            },
            None,
            true,
            true,
        );
        assert_eq!(ui.focus, FocusTarget::Float(id));
    }

    #[test]
    fn close_focused_float_restores_focus() {
        let mut ui = Model::default();
        let panel_id = ui.insert_panel(
            "Agent",
            Box::new(AssistantModel::default()),
            PanelSide::Right,
            PanelSize::Percent(35),
        );
        ui.focus_panel(panel_id);
        assert_eq!(ui.focus, FocusTarget::Panel(panel_id));

        let float_id = ui.create_float(
            Box::new(TextFloatModel::default()),
            Placement::Centered {
                width: 40,
                height: 10,
            },
            None,
            false,
            true,
        );
        assert_eq!(ui.focus, FocusTarget::Float(float_id));

        ui.close_float(float_id);
        // Focus should return to the panel
        assert_eq!(ui.focus, FocusTarget::Panel(panel_id));
    }

    #[test]
    fn float_model_downcast() {
        let mut ui = Model::default();
        let id = ui.create_float(
            Box::new(TextFloatModel {
                blocks: vec![RenderBlock {
                    text: "hello".into(),
                    style: None,
                }],
            }),
            Placement::Centered {
                width: 40,
                height: 10,
            },
            None,
            false,
            false,
        );
        let model = ui.float_model_mut::<TextFloatModel>(id).unwrap();
        assert_eq!(model.blocks.len(), 1);
        assert_eq!(model.blocks[0].text, "hello");
    }

    // ─── Panel toggle ───────────────────────────────────────────────

    #[test]
    fn toggle_panel_visibility() {
        let mut ui = Model::default();
        let id = ui.insert_panel(
            "Files",
            Box::new(TreePanelModel::default()),
            PanelSide::Left,
            PanelSize::fixed(30),
        );
        assert!(ui.panels[id].visible);
        assert_eq!(ui.toggle_panel(id), Some(false));
        assert!(!ui.panels[id].visible);
        assert_eq!(ui.toggle_panel(id), Some(true));
        assert!(ui.panels[id].visible);
    }

    #[test]
    fn toggle_focused_panel_hidden_restores_focus() {
        let mut ui = Model::default();
        let id = ui.insert_panel(
            "Files",
            Box::new(TreePanelModel::default()),
            PanelSide::Left,
            PanelSize::fixed(30),
        );
        ui.focus_panel(id);
        assert_eq!(ui.focus, FocusTarget::Panel(id));
        ui.toggle_panel(id); // hide it
        assert_eq!(ui.focus, FocusTarget::Editor);
    }

    // ─── Focus history ──────────────────────────────────────────────

    #[test]
    fn focus_history_push_pop() {
        let mut ui = Model::default();
        let panel_id = ui.insert_panel(
            "Agent",
            Box::new(AssistantModel::default()),
            PanelSide::Right,
            PanelSize::Percent(35),
        );
        assert_eq!(ui.focus, FocusTarget::Editor);

        ui.push_focus(FocusTarget::Panel(panel_id));
        assert_eq!(ui.focus, FocusTarget::Panel(panel_id));

        let float_id = ui.create_float(
            Box::new(TextFloatModel::default()),
            Placement::Centered {
                width: 40,
                height: 10,
            },
            None,
            false,
            true,
        );
        assert_eq!(ui.focus, FocusTarget::Float(float_id));

        ui.pop_focus();
        assert_eq!(ui.focus, FocusTarget::Panel(panel_id));

        ui.pop_focus();
        assert_eq!(ui.focus, FocusTarget::Editor);

        // Popping empty history goes to Editor
        ui.pop_focus();
        assert_eq!(ui.focus, FocusTarget::Editor);
    }

    #[test]
    fn push_same_focus_is_no_op() {
        let mut ui = Model::default();
        ui.push_focus(FocusTarget::Editor);
        assert!(ui.focus_history.is_empty());
    }
}
