//! Shared UI model for frontend-agnostic rendering.
//!
//! Commands mutate `Model` directly. Frontends read it and render.
//! No action enum indirection — the model is the single source of truth.
//!
//! Layer and panel content uses trait objects (`Box<dyn LayerModel>`,
//! `Box<dyn PanelModel>`) instead of enums, so new model types can be
//! added without modifying this module.

mod models;

pub use models::{
    AcpChatEntry, AcpModel, AcpPlanItem, AcpPlanStatus, CompletionItem, CompletionModel,
    PickerCell, PickerColumnHeader, PickerItemData, PickerModel, PickerPreview, PickerRow,
    PromptModel,
};
// Re-export PluginPanelModel (defined here, not in models submodule)

use std::any::Any;
use std::fmt::Debug;
use std::path::PathBuf;

use slotmap::SlotMap;

slotmap::new_key_type! {
    pub struct PanelId;
}

/// Marker type for layer IDs.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum LayerKind {}

/// Stable ID for a layer. Generated by `Model::next_layer_id()`.
pub type LayerId = crate::id::Id<LayerKind>;

// ─── Layer / Panel model traits ─────────────────────────────────────────

/// Trait for layer content models. Implemented by any type that can be
/// stored as layer content in `Model`. Uses `Any` for downcasting to
/// concrete types at render time.
pub trait LayerModel: Debug + Send + Sync + Any {
    fn as_any(&self) -> &dyn Any;
    fn as_any_mut(&mut self) -> &mut dyn Any;
    /// Identifier for this model type (e.g. "picker", "prompt").
    fn tag(&self) -> &str;
}

/// Trait for panel content models. Same pattern as `LayerModel`.
pub trait PanelModel: Debug + Send + Sync + Any {
    fn as_any(&self) -> &dyn Any;
    fn as_any_mut(&mut self) -> &mut dyn Any;
    /// Identifier for this model type (e.g. "chat", "list", "tree").
    fn tag(&self) -> &str;
}

/// Implement `LayerModel` for a concrete type with a static tag.
#[macro_export]
macro_rules! impl_layer_model {
    ($ty:ty, $tag:expr) => {
        impl $crate::model::LayerModel for $ty {
            fn as_any(&self) -> &dyn ::std::any::Any {
                self
            }
            fn as_any_mut(&mut self) -> &mut dyn ::std::any::Any {
                self
            }
            fn tag(&self) -> &str {
                $tag
            }
        }
    };
}

/// Implement `PanelModel` for a concrete type with a static tag.
#[macro_export]
macro_rules! impl_panel_model {
    ($ty:ty, $tag:expr) => {
        impl $crate::model::PanelModel for $ty {
            fn as_any(&self) -> &dyn ::std::any::Any {
                self
            }
            fn as_any_mut(&mut self) -> &mut dyn ::std::any::Any {
                self
            }
            fn tag(&self) -> &str {
                $tag
            }
        }
    };
}

// ─── Built-in LayerModel impls ──────────────────────────────────────────

crate::impl_layer_model!(PickerModel, "picker");
crate::impl_layer_model!(PromptModel, "prompt");
crate::impl_layer_model!(CompletionModel, "completion");
crate::impl_layer_model!(PluginLayerModel, "plugin");

// ─── Built-in PanelModel impls ──────────────────────────────────────────

crate::impl_panel_model!(AcpModel, "acp-panel");
crate::impl_panel_model!(ListPanelModel, "list");
crate::impl_panel_model!(TreePanelModel, "tree");
crate::impl_panel_model!(BlocksPanelModel, "blocks");
crate::impl_panel_model!(PluginPanelModel, "plugin_panel");

// ─── Model ────────────────────────────────────────────────────────────

/// Root UI state. Commands mutate this; frontends render it.
#[derive(Debug)]
pub struct Model {
    /// Ordered layer stack (bottom to top), rendered in order.
    pub layers: Vec<LayerEntry>,

    /// Persistent side panels (ACP, file tree, diagnostics, etc.).
    /// SlotMap for stable IDs — panels can be added/removed without index shifts.
    pub panels: SlotMap<PanelId, PanelEntry>,

    /// Status line / transient notifications.
    pub status: Option<StatusMessage>,

    /// What currently has input focus.
    pub focus: FocusTarget,

    /// Counter for allocating unique layer IDs.
    next_layer_id: usize,
}

impl Default for Model {
    fn default() -> Self {
        Self {
            layers: Vec::new(),
            panels: SlotMap::default(),
            status: None,
            focus: FocusTarget::Editor,
            next_layer_id: 0,
        }
    }
}

impl Model {
    /// Allocate a new layer ID. Call when pushing a layer.
    pub fn next_layer_id(&mut self) -> LayerId {
        let id = LayerId::new(self.next_layer_id);
        self.next_layer_id = self.next_layer_id.saturating_add(1);
        id
    }

    /// Push a new layer onto the stack and focus it. Returns its `LayerId`.
    pub fn push_layer(&mut self, content: Box<dyn LayerModel>, placement: Placement) -> LayerId {
        let id = self.next_layer_id();
        self.layers.push(LayerEntry {
            id,
            content,
            placement,
        });
        self.focus = FocusTarget::Layer(id);
        id
    }

    /// Remove a layer by ID. Returns `true` if found. Resets focus to editor
    /// if the removed layer was focused.
    pub fn remove_layer(&mut self, id: LayerId) -> bool {
        let was_focused = self.focus == FocusTarget::Layer(id);
        let idx = self.layers.iter().position(|l| l.id == id);
        if let Some(idx) = idx {
            self.layers.remove(idx);
            if was_focused {
                self.focus = self
                    .layers
                    .last()
                    .map(|l| FocusTarget::Layer(l.id))
                    .unwrap_or(FocusTarget::Editor);
            }
            true
        } else {
            false
        }
    }

    /// Pop the topmost layer. Returns its entry if the stack was non-empty.
    pub fn pop_layer(&mut self) -> Option<LayerEntry> {
        let entry = self.layers.pop();
        if let Some(ref e) = entry {
            if self.focus == FocusTarget::Layer(e.id) {
                self.focus = self
                    .layers
                    .last()
                    .map(|l| FocusTarget::Layer(l.id))
                    .unwrap_or(FocusTarget::Editor);
            }
        }
        entry
    }

    /// Get a reference to the topmost layer, if any.
    pub fn top_layer(&self) -> Option<&LayerEntry> {
        self.layers.last()
    }

    /// Get a mutable reference to a layer by ID.
    pub fn layer_mut(&mut self, id: LayerId) -> Option<&mut LayerEntry> {
        self.layers.iter_mut().find(|l| l.id == id)
    }

    /// Downcast a layer's content to a concrete model type.
    pub fn layer_model_mut<M: 'static>(&mut self, id: LayerId) -> Option<&mut M> {
        self.layer_mut(id)
            .and_then(|l| l.content.as_any_mut().downcast_mut::<M>())
    }

    /// Check if any layer contains a model of type `M`.
    pub fn has_layer<M: 'static>(&self) -> bool {
        self.layers.iter().any(|l| l.content.as_any().is::<M>())
    }

    /// Insert a panel. Returns its `PanelId`.
    pub fn insert_panel(
        &mut self,
        title: impl Into<String>,
        content: Box<dyn PanelModel>,
        side: PanelSide,
        size: PanelSize,
    ) -> PanelId {
        let title = title.into();
        self.panels.insert_with_key(|id| PanelEntry {
            id,
            title,
            content,
            side,
            size,
        })
    }

    /// Downcast a panel's content to a concrete model type.
    pub fn panel_model_mut<M: 'static>(&mut self, id: PanelId) -> Option<&mut M> {
        self.panels
            .get_mut(id)
            .and_then(|p| p.content.as_any_mut().downcast_mut::<M>())
    }

    /// Remove a panel by ID. Returns `true` if found.
    pub fn remove_panel(&mut self, id: PanelId) -> bool {
        if self.focus == FocusTarget::Panel(id) {
            self.focus = FocusTarget::Editor;
        }
        self.panels.remove(id).is_some()
    }

    /// Set the status message. Pass `None` to clear.
    pub fn set_status(&mut self, msg: Option<StatusMessage>) {
        self.status = msg;
    }

    /// Find the first layer matching a predicate.
    pub fn find_layer(&self, predicate: impl Fn(&LayerEntry) -> bool) -> Option<&LayerEntry> {
        self.layers.iter().find(|l| predicate(l))
    }
}

// ─── Layer / Panel entries ──────────────────────────────────────────────

/// A single layer in the compositor stack.
pub struct LayerEntry {
    pub id: LayerId,
    /// Typed content model for rendering. Downcast to concrete type via `as_any`.
    pub content: Box<dyn LayerModel>,
    pub placement: Placement,
}

// Manual Debug because Box<dyn LayerModel> is Debug but we want a cleaner output.
impl Debug for LayerEntry {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("LayerEntry")
            .field("id", &self.id)
            .field("tag", &self.content.tag())
            .field("placement", &self.placement)
            .finish()
    }
}

/// How a layer is positioned.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Placement {
    Fullscreen,
    Centered {
        width: u16,
        height: u16,
    },
    Float {
        x: u16,
        y: u16,
        width: u16,
        height: u16,
    },
}

/// Plugin layer model — structured data for frontend rendering.
#[derive(Debug, Clone)]
pub struct PluginLayerModel {
    pub plugin_id: String,
    pub title: String,
    pub content: Vec<RenderBlock>,
}

/// Styled text block or interactive region for plugin rendering.
#[derive(Debug, Clone)]
pub struct RenderBlock {
    pub text: String,
    pub style: Option<crate::graphics::Style>,
}

/// A persistent docked panel — generic container for side content.
///
/// The content's `tag()` identifies the model type. The `title` field
/// is for display. Event routing uses the panel's `PanelId` and the
/// model's `tag()`.
pub struct PanelEntry {
    pub id: PanelId,
    /// Display title shown in the panel header (e.g. "Agent", "Files").
    pub title: String,
    /// Typed content model for rendering. Downcast to concrete type via `as_any`.
    pub content: Box<dyn PanelModel>,
    /// Which edge the panel is docked to.
    pub side: PanelSide,
    /// How much space the panel takes.
    pub size: PanelSize,
}

impl PanelEntry {
    /// The content model's tag (e.g. "chat", "list", "tree").
    pub fn tag(&self) -> &str {
        self.content.tag()
    }
}

impl Debug for PanelEntry {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("PanelEntry")
            .field("id", &self.id)
            .field("title", &self.title)
            .field("tag", &self.content.tag())
            .field("side", &self.side)
            .field("size", &self.size)
            .finish()
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PanelSide {
    Left,
    Right,
    Bottom,
}

/// Panel sizing — alias for the shared `Size` enum from layout.
pub type PanelSize = crate::layout::Size;

/// Freeform styled blocks panel model. For custom plugin UIs that don't
/// fit the chat/list/tree patterns.
#[derive(Debug, Clone, Default)]
pub struct BlocksPanelModel {
    pub blocks: Vec<RenderBlock>,
}

/// List panel model — flat item list with selection.
#[derive(Debug, Clone, Default)]
pub struct ListPanelModel {
    pub items: Vec<ListPanelItem>,
    pub selection: Option<usize>,
}

/// An item in a list panel.
#[derive(Debug, Clone)]
pub struct ListPanelItem {
    pub text: String,
    pub detail: Option<String>,
    pub severity: Option<String>,
    pub path: Option<PathBuf>,
    pub line: Option<usize>,
}

/// Tree panel model — hierarchical expandable nodes.
#[derive(Debug, Clone, Default)]
pub struct TreePanelModel {
    pub root: PathBuf,
    pub items: Vec<TreePanelNode>,
    pub selection: Option<usize>,
}

/// A node in a tree panel.
#[derive(Debug, Clone)]
pub struct TreePanelNode {
    pub label: String,
    pub path: Option<PathBuf>,
    pub is_dir: bool,
    pub depth: usize,
    pub expanded: bool,
}

/// Plugin panel model — lightweight metadata for a Lua-rendered panel.
///
/// The actual rendering is done by the Lua callback; this model just holds
/// the metadata needed for the compositor to allocate space and for the
/// PluginPanel Component to find its callbacks.
#[derive(Debug, Clone)]
pub struct PluginPanelModel {
    pub plugin_name: String,
    pub panel_id: String,
    pub render_callback_id: u64,
    pub event_callback_id: Option<u64>,
}

#[derive(Debug, Clone)]
pub struct StatusMessage {
    pub text: String,
    pub timeout_ms: Option<u64>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum FocusTarget {
    Editor,
    Layer(LayerId),
    Panel(PanelId),
}

// Re-export the old type alias for transition period.
pub type ChatPanelModel = AcpModel;

#[cfg(test)]
mod tests {
    use super::*;

    // ─── Layer lifecycle ────────────────────────────────────────────

    #[test]
    fn push_layer_assigns_unique_ids() {
        let mut ui = Model::default();
        let id1 = ui.push_layer(Box::new(PickerModel::default()), Placement::Fullscreen);
        let id2 = ui.push_layer(Box::new(PromptModel::default()), Placement::Fullscreen);
        assert_ne!(id1, id2);
        assert_eq!(ui.layers.len(), 2);
    }

    #[test]
    fn push_layer_focuses_new_layer() {
        let mut ui = Model::default();
        assert_eq!(ui.focus, FocusTarget::Editor);
        let id = ui.push_layer(Box::new(PickerModel::default()), Placement::Fullscreen);
        assert_eq!(ui.focus, FocusTarget::Layer(id));
    }

    #[test]
    fn pop_layer_restores_focus() {
        let mut ui = Model::default();
        let id1 = ui.push_layer(Box::new(PickerModel::default()), Placement::Fullscreen);
        let _id2 = ui.push_layer(Box::new(PromptModel::default()), Placement::Fullscreen);
        ui.pop_layer();
        assert_eq!(ui.focus, FocusTarget::Layer(id1));
        ui.pop_layer();
        assert_eq!(ui.focus, FocusTarget::Editor);
    }

    #[test]
    fn pop_empty_returns_none() {
        let mut ui = Model::default();
        assert!(ui.pop_layer().is_none());
    }

    #[test]
    fn remove_layer_by_id() {
        let mut ui = Model::default();
        let id1 = ui.push_layer(Box::new(PickerModel::default()), Placement::Fullscreen);
        let id2 = ui.push_layer(Box::new(PromptModel::default()), Placement::Fullscreen);
        assert!(ui.remove_layer(id1));
        assert_eq!(ui.layers.len(), 1);
        assert_eq!(ui.layers[0].id, id2);
    }

    #[test]
    fn remove_focused_layer_refocuses() {
        let mut ui = Model::default();
        let id1 = ui.push_layer(Box::new(PickerModel::default()), Placement::Fullscreen);
        let id2 = ui.push_layer(Box::new(PromptModel::default()), Placement::Fullscreen);
        assert_eq!(ui.focus, FocusTarget::Layer(id2));
        ui.remove_layer(id2);
        assert_eq!(ui.focus, FocusTarget::Layer(id1));
    }

    #[test]
    fn remove_nonexistent_layer_returns_false() {
        let mut ui = Model::default();
        assert!(!ui.remove_layer(LayerId::new(999)));
    }

    // ─── Layer model access (generic) ───────────────────────────────

    #[test]
    fn layer_model_mut_downcasts_correctly() {
        let mut ui = Model::default();
        let id = ui.push_layer(Box::new(PickerModel::default()), Placement::Fullscreen);
        let model = ui.layer_model_mut::<PickerModel>(id).unwrap();
        model.query = "test".into();
        assert_eq!(ui.layer_model_mut::<PickerModel>(id).unwrap().query, "test");
    }

    #[test]
    fn layer_model_mut_returns_none_for_wrong_type() {
        let mut ui = Model::default();
        let id = ui.push_layer(Box::new(PickerModel::default()), Placement::Fullscreen);
        assert!(ui.layer_model_mut::<PromptModel>(id).is_none());
    }

    #[test]
    fn has_layer_reflects_state() {
        let mut ui = Model::default();
        assert!(!ui.has_layer::<PickerModel>());
        let id = ui.push_layer(Box::new(PickerModel::default()), Placement::Fullscreen);
        assert!(ui.has_layer::<PickerModel>());
        ui.remove_layer(id);
        assert!(!ui.has_layer::<PickerModel>());
    }

    // ─── Panel lifecycle ────────────────────────────────────────────

    #[test]
    fn insert_and_remove_panel() {
        let mut ui = Model::default();
        let id = ui.insert_panel(
            "Test Panel",
            Box::new(BlocksPanelModel::default()),
            PanelSide::Right,
            PanelSize::Percent(30),
        );
        assert_eq!(ui.panels.len(), 1);
        assert_eq!(ui.panels[id].tag(), "blocks");
        assert_eq!(ui.panels[id].title, "Test Panel");
        assert!(ui.remove_panel(id));
        assert_eq!(ui.panels.len(), 0);
    }

    #[test]
    fn remove_focused_panel_resets_focus() {
        let mut ui = Model::default();
        let id = ui.insert_panel(
            "Agent",
            Box::new(AcpModel::default()),
            PanelSide::Right,
            PanelSize::Percent(35),
        );
        ui.focus = FocusTarget::Panel(id);
        ui.remove_panel(id);
        assert_eq!(ui.focus, FocusTarget::Editor);
    }

    #[test]
    fn panel_model_mut_downcasts_correctly() {
        let mut ui = Model::default();
        let id = ui.insert_panel(
            "Agent",
            Box::new(AcpModel::default()),
            PanelSide::Right,
            PanelSize::Percent(35),
        );
        let model = ui.panel_model_mut::<AcpModel>(id).unwrap();
        model.agent_name = "Claude Code".into();
        assert_eq!(
            ui.panel_model_mut::<AcpModel>(id).unwrap().agent_name,
            "Claude Code"
        );
    }

    // ─── Status ─────────────────────────────────────────────────────

    #[test]
    fn set_and_clear_status() {
        let mut ui = Model::default();
        assert!(ui.status.is_none());
        ui.set_status(Some(StatusMessage {
            text: "hello".into(),
            timeout_ms: Some(3000),
        }));
        assert_eq!(ui.status.as_ref().unwrap().text, "hello");
        ui.set_status(None);
        assert!(ui.status.is_none());
    }

    // ─── Multiple layers + panels coexist ───────────────────────────

    #[test]
    fn layers_and_panels_independent() {
        let mut ui = Model::default();
        let layer_id = ui.push_layer(Box::new(PickerModel::default()), Placement::Fullscreen);
        let panel_id = ui.insert_panel(
            "Files",
            Box::new(TreePanelModel::default()),
            PanelSide::Left,
            PanelSize::fixed(30),
        );
        assert_eq!(ui.layers.len(), 1);
        assert_eq!(ui.panels.len(), 1);

        ui.remove_layer(layer_id);
        assert_eq!(ui.layers.len(), 0);
        assert_eq!(ui.panels.len(), 1);

        ui.push_layer(Box::new(PromptModel::default()), Placement::Fullscreen);
        ui.remove_panel(panel_id);
        assert_eq!(ui.layers.len(), 1);
        assert_eq!(ui.panels.len(), 0);
    }
}
