name = "typescript-language-server"
kind = "lsp"
description = "TypeScript and JavaScript language server"
homepage = "https://github.com/typescript-language-server/typescript-language-server"
aliases = ["tsserver", "typescript-lsp"]
languages = ["typescript", "javascript"]

[version]
tag-source = "npm:typescript-language-server"

[[artifact]]
os = "windows"
arch = "x86_64"
source = { npm = "typescript-language-server", bin = "typescript-language-server" }
bin = "typescript-language-server"

[[artifact]]
os = "linux"
arch = "x86_64"
source = { npm = "typescript-language-server", bin = "typescript-language-server" }
bin = "typescript-language-server"

[[artifact]]
os = "macos"
arch = "aarch64"
source = { npm = "typescript-language-server", bin = "typescript-language-server" }
bin = "typescript-language-server"
